In [1]:
import pandas as pd
import re

In [2]:
df_JCNBM = pd.read_csv('../../../datasets/NSC_BND_M20.csv')

C:\Users\01-10\AppData\Local\Temp\ipykernel_11476\1035179799.py:1: DtypeWarning: Columns (3,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_JCNBM = pd.read_csv('../../../datasets/NSC_BND_M20.csv')

In [3]:
df_JCNBM.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137163 entries, 0 to 137162
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Unnamed: 0          137163 non-null  int64
 1   _id                 137163 non-null  object
 2   RN_INDI             137163 non-null  int64
 3   BTH_YYYY            137163 non-null  object
 4   DTH_YYYYMM          10269 non-null   float64
 5   COD1                8473 non-null    object
 6   COD2                998 non-null     object
 7   RN_KEY              137163 non-null  int64
 8   RN_INST             137163 non-null  int64
 9   MDCARE_STRT_DT      137163 non-null  int64
 10  FORM_CD             137163 non-null  int64
 11  MCARE_SUBJ_CD       137163 non-null  int64
 12  SICK_SYM1           137163 non-null  object
 13  OFIJ_TYPE           134428 non-null  object
 14  OPRTN_YN            137163 non-null  int64
 15  MDCARE_DD_CNT       137163 non-null  int64
 16  VSHSP_DD_CNT        137163 non-null  int64
 17  TOT_PRSC_DD_CNT     137163 non-null  int64
 18  MCARE_RSLT_TYPE     133958 non-null  float64
 19  EDC_ADD_RT          137163 non-null  float64
 20  ED_RC_TOT_AMT       137163 non-null  int64
 21  EDC_SBA             137163 non-null  int64
 22  EDC_INSUR_BRDN_AMT  137163 non-null  int64
 23  STD_YYYY            137163 non-null  int64
dtypes: float64(3), int64(15), object(6)
memory usage: 25.1+ MB

In [4]:
df_JCNBM = df_JCNBM[['SICK_SYM1','TOT_PRSC_DD_CNT', 'MCARE_RSLT_TYPE', 'EDC_ADD_RT','ED_RC_TOT_AMT', 'EDC_SBA']]
df_JCNBM

,SICK_SYM1,TOT_PRSC_DD_CNT,MCARE_RSLT_TYPE,EDC_ADD_RT,ED_RC_TOT_AMT,EDC_SBA
0,L028,3,5.0,0.15,10590,3000
1,J030,2,5.0,0.15,16520,4950
2,J030,3,5.0,0.15,27620,9000
3,K291,3,5.0,0.15,12920,3000
4,M545,0,5.0,0.15,14230,3000
...,...,...,...,...,...,...
137158,J209,0,1.0,0.15,11280,2300
137159,J209,0,1.0,0.15,19640,3700
137160,J209,0,1.0,0.15,13470,2800
137161,J209,0,1.0,0.15,13530,2600
137162,J00,0,1.0,0.25,21730,6800

In [5]:
def convertSICK_SYM(sick_sym) : 
    if len(sick_sym) < 3 :
        return None
    else : 
        return sick_sym[:3]

In [6]:
convertSICK_SYM('J209'), convertSICK_SYM('F_')

('J20', None)

In [7]:
df_JCNBM['SICK_SYM2'] = df_JCNBM['SICK_SYM1'].apply(convertSICK_SYM)

In [8]:
df_JCNBM['SICK_SYM2'].value_counts()

J20    8917
I10    8427
J03    4187
M54    3904
J06    3460
       ...
G97       1
K01       1
S28       1
I72       1
P28       1
Name: SICK_SYM2, Length: 747, dtype: int64

In [9]:
df_JCNBM = df_JCNBM.dropna()
df_JCNBM.isnull().sum()

SICK_SYM1          0
TOT_PRSC_DD_CNT    0
MCARE_RSLT_TYPE    0
EDC_ADD_RT         0
ED_RC_TOT_AMT      0
EDC_SBA            0
SICK_SYM2          0
dtype: int64

In [10]:
df_JCNBM[:2]

,SICK_SYM1,TOT_PRSC_DD_CNT,MCARE_RSLT_TYPE,EDC_ADD_RT,ED_RC_TOT_AMT,EDC_SBA,SICK_SYM2
0,L028,3,5.0,0.15,10590,3000,L02
1,J030,2,5.0,0.15,16520,4950,J03

In [19]:
target_list = df_JCNBM['SICK_SYM2'].value_counts().index.to_list()
target_list

['J20',
 'I10',
 'J03',
 'M54',
 'J06',
 'M17',
 'J30',
 'E11',
 'J01',
 'J02',
 'K29',
 'J00',
 'L23',
 'H10',
 'J04',
 'J45',
 'M51',
 'M75',
 'B35',
 'J32',
 'H66',
 'N18',
 'A09',
 'K21',
 'M79',
 'S33',
 'J21',
 'J40',
 'H04',
 'H52',
 'M48',
 'H65',
 'L50',
 'M47',
 'I11',
 'M13',
 'M50',
 'N30',
 'N40',
 'J31',
 'L02',
 'K25',
 'H25',
 'M25',
 'K59',
 'E78',
 'H60',
 'M65',
 'S93',
 'L30',
 'J18',
 'H00',
 'K52',
 'S63',
 'S61',
 'H16',
 'S83',
 'K58',
 'J34',
 'M19',
 'I20',
 'M77',
 'L20',
 'S01',
 'I84',
 'S13',
 'I63',
 'M81',
 'L03',
 'E14',
 'M72',
 'B02',
 'L24',
 'H81',
 'M15',
 'S43',
 'J22',
 'L21',
 'J36',
 'E03',
 'H40',
 'R10',
 'K27',
 'S52',
 'H35',
 'C22',
 'S62',
 'E05',
 'N34',
 'L84',
 'L04',
 'G44',
 'S23',
 'J35',
 'C16',
 'K76',
 'K12',
 'H11',
 'R51',
 'M10',
 'N41',
 'R07',
 'B30',
 'L25',
 'I50',
 'A08',
 'R42',
 'L08',
 'N39',
 'R50',
 'S92',
 'B07',
 'L40',
 'K30',
 'K26',
 'C90',
 'G43',
 'E04',
 'L29',
 'M23',
 'H36',
 'S82',
 'M53',
 'G47',
 'B00',
 'M62',
 'S32',
 'H93',
 'S22',
 'H61',
 'J41',
 'J37',
 'H90',
 'D50',
 'J42',
 'N31',
 'Z96',
 'A04',
 'L60',
 'T15',
 'J15',
 'L28',
 'J44',
 'N20',
 'Z94',
 'S53',
 'J38',
 'I69',
 'C20',
 'T23',
 'C19',
 'M06',
 'H01',
 'S80',
 'I48',
 'L73',
 'I67',
 'I25',
 'L01',
 'M43',
 'I61',
 'S81',
 'M24',
 'S00',
 'S20',
 'R31',
 'S91',
 'T14',
 'R04',
 'E10',
 'S42',
 'M76',
 'R11',
 'G20',
 'G54',
 'H02',
 'S90',
 'C18',
 'H26',
 'I83',
 'L63',
 'D23',
 'K31',
 'S60',
 'J39',
 'E06',
 'G57',
 'G81',
 'S02',
 'D47',
 'G46',
 'J47',
 'K73',
 'M22',
 'C73',
 'K63',
 'I73',
 'R05',
 'H68',
 'S05',
 'E87',
 'S50',
 'K35',
 'G56',
 'M05',
 'S73',
 'H19',
 'S46',
 'K70',
 'K60',
 'L72',
 'M94',
 'M41',
 'D64',
 'C25',
 'B08',
 'L91',
 'N02',
 'C15',
 'M67',
 'K74',
 'I70',
 'G45',
 'L85',
 'T00',
 'H73',
 'H20',
 'H43',
 'K80',
 'C32',
 'J46',
 'S66',
 'D17',
 'S51',
 'D34',
 'C40',
 'D12',
 'H91',
 'N10',
 'G63',
 'L51',
 'P59',
 'R00',
 'S06',
 'E13',
 'S67',
 'S72',
 'E07',
 'T17',
 'R60',
 'I42',
 'D24',
 'R06',
 'T22',
 'K61',
 'S70',
 'L27',
 'M20',
 'B36',
 'R52',
 'T16',
 'D21',
 'T24',
 'D35',
 'G50',
 'J05',
 'G53',
 'L13',
 'S86',
 'L70',
 'H34',
 'R80',
 'H44',
 'J43',
 'H50',
 'I66',
 'S30',
 'C69',
 'I12',
 'Z03',
 'M70',
 'M16',
 'M46',
 'L42',
 'C43',
 'K62',
 'K11',
 'K92',
 'I65',
 'G30',
 'K14',
 'B37',
 'Z48',
 'C67',
 'I87',
 'T21',
 'M12',
 'K56',
 'E23',
 'N13',
 'C34',
 'R94',
 'S03',
 'Z71',
 'J33',
 'S40',
 'I49',
 'K40',
 'T31',
 'M60',
 'E50',
 'A05',
 'R12',
 'R22',
 'T63',
 'T78',
 'M80',
 'R63',
 'Z98',
 'D69',
 'R73',
 'E16',
 'M45',
 'A49',
 'K05',
 'G58',
 'G51',
 'H47',
 'C65',
 'T93',
 'M40',
 'J84',
 'L26',
 'K07',
 'R81',
 'N28',
 'M35',
 'R30',
 'M92',
 'T25',
 'M00',
 'T20',
 'H15',
 'L53',
 'L05',
 'C80',
 'M42',
 'M99',
 'K85',
 'D18',
 'R19',
 'S97',
 'H92',
 'C85',
 'T30',
 'I15',
 'H57',
 'C83',
 'G62',
 'R55',
 'B86',
 'G96',
 'N17',
 'H53',
 'S54',
 'R56',
 'G90',
 'G25',
 'M89',
 'R53',
 'G93',
 'K71',
 'D13',
 'R62',
 'B17',
 'B85',
 'G55',
 'I88',
 'E55',
 'C64',
 'D33',
 'H71',
 'L22',
 'S09',
 'R03',
 'K75',
 'D14',
 'K20',
 'T81',
 'B25',
 'H05',
 'H31',
 'N03',
 'M21',
 'S96',
 'N04',
 'R61',
 'L98',
 'M84',
 'L81',
 'L71',
 'M49',
 'H27',
 'E86',
 'D31',
 'N05',
 'I31',
 'K13',
 'B09',
 'K57',
 'N32',
 'Z01',
 'R91',
 'C44',
 'I71',
 'M14',
 'N21',
 'A69',
 'H33',
 'S41',
 'N06',
 'M96',
 'R25',
 'P38',
 'G99',
 'R92',
 'G22',
 'L56',
 'H62',
 'T08',
 'Z47',
 'M85',
 'L74',
 'R35',
 'Z00',
 'T84',
 'G03',
 'R59',
 'I45',
 'Z54',
 'H72',
 'A59',
 'K72',
 'H18',
 'G64',
 'R32',
 'B33',
 'N00',
 'T83',
 'S71',
 'G31',
 'I85',
 'H49',
 'S56',
 'C79',
 'M86',
 'Z13',
 'H17',
 'S99',
 'K86',
 'T92',
 'L64',
 'D48',
 'R09',
 'S21',
 'E22',
 'L80',
 'T79',
 'K81',
 'C78',
 'L82',
 'R01',
 'R21',
 'Q74',
 'G52',
 'S69',
 'R14',
 'H69',
 'S76',
 'T91',
 'B88',
 'J98',
 'R68',
 'T29',
 'M18',
 'S14',
 'J90',
 'I95',
 'J12',
 'G82',
 'T18',
 'S64',
 'R23',
 'A87',
 'Z52',
 'S31',
 'L90',
 'K82',
 'L55',
 'J69',
 'K77',
 'T13',
 'M71',
 'M11',
 'B18',
 'S68',
 'I78',
 'R20',
 'B34',
 'E24',
 'S34',
 'Z93',
 'G95',
 'D10',
 'T09',
 'S07',
 'P83',
 'Z97',
 'K37',
 'I60',
 'R49',
 'D44',
 'I51',
 'T60',
 'L43',
 'I35',
 'J93',
 'I80',
 'K83',
 'D38',
 'I21',
 'N12',
 'P22',
 'T26',
 'D30',
 'K08',
 'Z51',
 'B19',
 'M02',
 'P39',
 'A41',
 'M83',
 'S27',
 'R39',
 'H13',
 'R57',
 'T19',
 'Z12',
 'R43',
 'E66',
 'K50',
 'I47',
 'L65',
 'M61',
 'O47',
 'H83',
 'R15',
 'Z04',
 'D16',
 'T11',
 'L89',
 'C95',
 'J16',
 'D22',
 'N11',
 'T67',
 'S36',
 'G13',
 'S12',
 'G70',
 'D36',
 'I64',
 'G04',
 'R93',
 'K51',
 'M93',
 'L52',
 'T33',
 'H82',
 'H74',
 'Z22',
 'S57',
 'K04',
 'R69',
 'R79',
 'I89',
 'P36',
 'Z43',
 'T69',
 'L44',
 'I37',
 'L94',
 'L75',
 'D73',
 'R33',
 'H30',
 'K43',
 'H95',
 'K36',
 'L41',
 'E27',
 'R26',
 'R82',
 'R74',
 'T35',
 'T42',
 'R87',
 'H54',
 'S84',
 'Q66',
 'E83',
 'B43',
 'T98',
 'Q82',
 'C24',
 'N08',
 'P92',
 'G91',
 'Z24',
 'J81',
 'K28',
 'S39',
 'A06',
 'R89',
 'S11',
 'I24',
 'D11',
 'H28',
 'J17',
 'I13',
 'J85',
 'S87',
 'M07',
 'D41',
 'N19',
 'D75',
 'R36',
 'M87',
 'J94',
 'I62',
 'E88',
 'I72',
 'R17',
 'N42',
 'P07',
 'P24',
 'T65',
 'E73',
 'Q65',
 'E34',
 'P23',
 'Q80',
 'M73',
 'I46',
 'K22',
 'Z63',
 'I22',
 'N23',
 'S58',
 'D51',
 'N29',
 'G83',
 'Z45',
 'M95',
 'R13',
 'B69',
 'D01',
 'L66',
 'A75',
 'B98',
 'H80',
 'Q77',
 'M32',
 'D62',
 'D04',
 'Z25',
 'B27',
 'Z80',
 'L59',
 'Q68',
 'O34',
 'C91',
 'J92',
 'C08',
 'K10',
 'L95',
 'E80',
 'Z29',
 'M30',
 'T88',
 'I99',
 'S04',
 'H46',
 'S17',
 'Z08',
 'L11',
 'C66',
 'T04',
 'Z90',
 'D15',
 'K01',
 'H21',
 'E61',
 'D40',
 'K65',
 'I74',
 'K02',
 'I79',
 'R29',
 'A48',
 'T75',
 'G97',
 'S89',
 'S28',
 'I34',
 'H70',
 'H51',
 'R86',
 'C71',
 'L92',
 'S29',
 'D72',
 'K38',
 'G24',
 'G26',
 'J70',
 'S49',
 'P28']

In [12]:
target_list.index('L02'), target_list.index('J03')

(40, 2)

In [15]:
def applyIndexNumber(sick_sym_3):
    indexNumber = target_list.index(sick_sym_3)
    return indexNumber

In [18]:
df_JCNBM['SICK_SYM3'] = df_JCNBM['SICK_SYM2'].apply(applyIndexNumber)
df_JCNBM[:2]

C:\Users\01-10\AppData\Local\Temp\ipykernel_11476\4100169492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_JCNBM['SICK_SYM3'] = df_JCNBM['SICK_SYM2'].apply(applyIndexNumber)

,SICK_SYM1,TOT_PRSC_DD_CNT,MCARE_RSLT_TYPE,EDC_ADD_RT,ED_RC_TOT_AMT,EDC_SBA,SICK_SYM2,SICK_SYM3
0,L028,3,5.0,0.15,10590,3000,L02,40
1,J030,2,5.0,0.15,16520,4950,J03,2